apiVersion: apps/v1
kind: Deployment

metadata:
  name: django
  namespace: wrapzy

spec:
  replicas: 2
  revisionHistoryLimit: 5
  minReadySeconds: 10
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: django

  template:
    metadata:
      labels:
        app: django

    spec:
      containers:
        - name: django
          image: prapanjanprabhu/wrapzy:v4
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          startupProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3

          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DJANGO_SECRET_KEY

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: DB_HOST
              value: "mysql-service"

            - name: DB_PORT
              value: "3306"
            - name: DJANGO_DEBUG
              value: "False"

            - name: DJANGO_ALLOWED_HOSTS
              value: "*"

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ADMIN_USERNAME

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ADMIN_PASSWORD

          command: ["sh", "-c"]

          args:
            - exec gunicorn P1.wsgi:application --bind 0.0.0.0:8000 --workers 2 --access-logfile -
